-- Crear tabla gp_ls_resultados_agua si no existe
CREATE TABLE IF NOT EXISTS `gp_ls_resultados_agua` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `analitica_id` bigint unsigned DEFAULT NULL,
  `tienda_id` bigint unsigned DEFAULT NULL,
  `fecha_muestra` date DEFAULT NULL,
  `donde_se_recoje_muestra` varchar(255) DEFAULT NULL,
  `numero_muestras` int DEFAULT NULL,
  `numero_factura` varchar(255) DEFAULT NULL,
  `producto` varchar(255) DEFAULT NULL,
  `estado_analitica` varchar(255) NOT NULL DEFAULT 'sin_iniciar',
  `E_coli_valor` varchar(255) DEFAULT NULL,
  `E_coli_resultado` varchar(255) DEFAULT NULL,
  `coliformes_totales_valor` varchar(255) DEFAULT NULL,
  `coliformes_totales_resultado` varchar(255) DEFAULT NULL,
  `enterococos_valor` varchar(255) DEFAULT NULL,
  `enterococos_resultado` varchar(255) DEFAULT NULL,
  `amonio_valor` varchar(255) DEFAULT NULL,
  `amonio_resultado` varchar(255) DEFAULT NULL,
  `nitritos_valor` varchar(255) DEFAULT NULL,
  `nitritos_resultado` varchar(255) DEFAULT NULL,
  `color_valor` varchar(255) DEFAULT NULL,
  `color_resultado` varchar(255) DEFAULT NULL,
  `sabor_valor` varchar(255) DEFAULT NULL,
  `sabor_resultado` varchar(255) DEFAULT NULL,
  `olor_valor` varchar(255) DEFAULT NULL,
  `olor_resultado` varchar(255) DEFAULT NULL,
  `conductividad_valor` varchar(255) DEFAULT NULL,
  `conductividad_resultado` varchar(255) DEFAULT NULL,
  `ph_valor` varchar(255) DEFAULT NULL,
  `ph_resultado` varchar(255) DEFAULT NULL,
  `turbidez_valor` varchar(255) DEFAULT NULL,
  `turbidez_resultado` varchar(255) DEFAULT NULL,
  `cloro_libre_valor` varchar(255) DEFAULT NULL,
  `cloro_libre_resultado` varchar(255) DEFAULT NULL,
  `cloro_combinado_valor` varchar(255) DEFAULT NULL,
  `cloro_combinado_resultado` varchar(255) DEFAULT NULL,
  `cloro_total_valor` varchar(255) DEFAULT NULL,
  `cloro_total_resultado` varchar(255) DEFAULT NULL,
  `cobre_valor` varchar(255) DEFAULT NULL,
  `cobre_resultado` varchar(255) DEFAULT NULL,
  `cromo_total_valor` varchar(255) DEFAULT NULL,
  `cromo_total_resultado` varchar(255) DEFAULT NULL,
  `niquel_valor` varchar(255) DEFAULT NULL,
  `niquel_resultado` varchar(255) DEFAULT NULL,
  `hierro_valor` varchar(255) DEFAULT NULL,
  `hierro_resultado` varchar(255) DEFAULT NULL,
  `cloruro_vinilo_valor` varchar(255) DEFAULT NULL,
  `cloruro_vinilo_resultado` varchar(255) DEFAULT NULL,
  `bisfenol_valor` varchar(255) DEFAULT NULL,
  `bisfenol_resultado` varchar(255) DEFAULT NULL,
  `archivos` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `resultados_agua_analitica_id_index` (`analitica_id`),
  KEY `resultados_agua_tienda_id_index` (`tienda_id`),
  KEY `resultados_agua_fecha_muestra_index` (`fecha_muestra`),
  CONSTRAINT `resultados_agua_analitica_id_foreign` FOREIGN KEY (`analitica_id`) REFERENCES `gp_ls_analiticas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
